* Quickroam
** Is your org-roam slow?

If you're like me, you think [[https://github.com/org-roam/org-roam][org-roam]] has the right idea, but the current implementation is not reliable or fast enough for day-to-day work.

1. The end-user commands take 5 seconds to get the minibuffer ready.
   - A [[https://edstrom.dev/czdfr/org-roam-fixes#jxbqt][workaround by memoizing]] works well most of the time, but if I create a new node and immediately want to insert it elsewhere, I have to wait for an idle timer to update the memoization.

2. Very large Org files take 10 seconds to save with =org-roam-db-autosync-mode=.
   - I can turn the mode off, but then I need to manually run =M-x org-roam-db-sync= every now and then!  Not great when I'm in the zone and writing.

As best I can tell by reading the source code, problems #1 and #2 are totally separate.  Problem #1 /should/ be fixable, but #2 arises from the fact that org-roam is very generalized -- for example, it lets you plug in user-defined functions to exclude or include a node.  That's nice and hackable, but it means that org-roam is forced to use Org functions to "properly" parse every file it scans, incurring all the penalties of doing so.

** Fix

This package fixes both of above problems via alternatives to common commands:

- =org-roam-node-find= -- use =quickroam-find=
- =org-roam-node-insert= -- use =quickroam-insert=

They don't look up the org-roam DB at all, and just rely on ripgrep.  That means the commands always find up-to-date hits, so you can now set =org-roam-db-update-on-save= to nil.  Though be aware that the backlinks will not update either until you do a =M-x org-roam-db-sync=.

** Setup

Install [[https://github.com/BurntSushi/ripgrep][ripgrep]] on your computer.  Then add to Emacs initfiles something like this, assuming you install packages with [[https://github.com/radian-software/straight.el][straight.el]]:

#+begin_src elisp
(use-package quickroam
  :straight (quickroam :type git :host github :repo "meedstrom/quickroam")
  :defer t)

(add-hook 'org-mode-hook #'quickroam-enable)
(global-set-key (kbd "<f2> f") #'quickroam-find) ;; or whatever key you use
(global-set-key (kbd "<f2> i") #'quickroam-insert)
#+end_src

** Future work

This package could be extended to collect all the data needed to populate the SQL database, so we can stop using =org-roam-db-sync= altogether.

We "just" have to design a better regexp.  As it is, it just grabs titles and IDs, which satisfies the current purpose.  Totally replacing =org-roam-db-sync= may limit org-roam's hackability, but perhaps it's worth that.

** Thanks

Inspired by [[https://emacs.ch/@laotang/112139767286378879][a Mastodon conversation]] with the [[https://github.com/rtrppl/orgrr][orgrr]] author :)
